eval_only: false

model:
  name: "toynet"
  mode: "unified"  # "metallographic", "spectral", "unified"
  
  # Image-related parameters
  image_backbone: "resnet18"  # "resnet18", "resnet50"
  
  # Spectral-related parameters
  spectral_input_dim: 1600  # Full spectrum length after transpose
  
  # Model architecture parameters
  hidden_dim: 256
  dropout: 0.2
  num_outputs: 1  # For DOS regression

data:
  dataset: "metallo"
  mode: "unified"  # "metallographic", "spectral", "unified"
  
  # Data directory containing DOS folders
  data_dir: ".dataset"  # Directory with DOS folders (e.g., 5.844339467/)
  
  # Data processing parameters
  split_ratios: [0.8, 0.1, 0.1]  # train, val, test
  images_per_dos: 30  # Number of images to use per DOS value
  spectra_per_dos: 2  # Number of spectra per DOS value
  process_images: false  # Whether to apply image preprocessing
  normalize_spectral: true  # Whether to normalize spectral data

training:
  seed: 42
  dataloader_num_workers: 4
  output_dir: "./output"
  learning_rate: !!float 1.0e-4
  warmup_steps: 100
  weight_decay: 0.01
  num_train_epochs: 10
  per_device_train_batch_size: 4  # Reduced for memory efficiency
  per_device_eval_batch_size: 8
  eval_accumulation_steps: 8
  save_total_limit: 3
  report_to: ["wandb"]
  logging_strategy: "steps"
  logging_steps: 50
  eval_strategy: "steps"
  eval_steps: 200
  save_steps: 200
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false

wandb:
  project: "metallo"
  entity: null
  name: ""
  tags: []
