eval_only: false

model:
  name: "toynet"
  mode: "spectral"  # Spectral-only mode
  
  # Spectral-related parameters
  spectral_input_dim: 100  # Length of each spectral segment
  
  # Model architecture parameters
  hidden_dim: 256
  dropout: 0.2
  num_outputs: 1  # For DOS regression

data:
  dataset: "metallo"
  mode: "spectral"  # Spectral-only mode
  
  # Data directory containing DOS folders
  data_dir: ".dataset"
  
  # Data processing parameters
  split_ratios: [0.8, 0.1, 0.1]  # train, val, test
  spectral_length: 100  # Length of each spectral segment
  normalize_spectral: true  # Whether to normalize spectral data

training:
  seed: 42
  dataloader_num_workers: 4
  output_dir: "./output/spectral_only"
  learning_rate: !!float 1.0e-3
  warmup_steps: 100
  weight_decay: 0.01
  num_train_epochs: 10
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 64
  eval_accumulation_steps: 8
  save_total_limit: 3
  report_to: ["wandb"]
  logging_strategy: "steps"
  logging_steps: 50
  eval_strategy: "steps"
  eval_steps: 200
  save_steps: 200
  save_strategy: "steps"
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false

wandb:
  project: "metallo"
  entity: null
  name: "spectral-only-experiment"
  tags: []